### ISSUE TITLE
Testing it with a new robot

### ISSUE THREAD

**Issue by prakharg01** [jcnorby/global_body_planner#3]
According to the paper:- https://www.andrew.cmu.edu/user/amj1/papers/IROS2020_Fast_Global_Motion_Planning.pdf

To deploy this algorithm on a custom quadruped robot, what are the minimal set of parameters I have to change? Where exactly do I fill in the kinematic and dynamic constraints?

**Comment by jcnorby** [comment]
I would recommend adapting the version in [Quad-SDK](https://github.com/robomechanics/quad-sdk/tree/main/global_body_planner) as there have been lots of good changes since then, as well as better documentation and descriptions of the parameters. That said, in both implementations all of these parameters are stored in the PlannerConfig struct - things like the robot dimensions and terrain clearances, mass, and peak forces should be tuned to the particular model.

**Comment by prakharg01** [comment]
> I would recommend adapting the version in [Quad-SDK](https://github.com/robomechanics/quad-sdk/tree/main/global_body_planner) as there have been lots of good changes since then, as well as better documentation and descriptions of the parameters. That said, in both implementations all of these parameters are stored in the PlannerConfig struct - things like the robot dimensions and terrain clearances, mass, and peak forces should be tuned to the particular model.

Okay, thanks a lot!. When can we expect the documentation to add a new robot to QUAD SDK?

**Comment by jcnorby** [comment]
That's a good question, and good to know that folks are looking for it! I just noticed that we didn't add the robot-specific parameters to the global_body_planner readme (since those parameters are in the robot yaml files), we should do that soon. I will talk to the team and see what the timeline will be on that documentation but hopefully soon. For now you can look at the Spirit and A1 urdfs and yaml files to see how we handle different robots, and copy those for your own platform.

**Comment by prakharg01** [comment]
Oh okay, Thanks a lot!

I'm mainly interested in using this planner for a use case, that's why I was trying to use this instead of Quad SDK. I'm facing some issues with running quad SDK currently, that I'm trying to resolve.

I just wanted to know is there some kind of visualization available for the trajectories generated just like XPP in TOWR by Alexander Winkler?
